AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-layer-app
  Sample SAM Template for lambda-layer-app

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Hello_world_function
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref layerlibs
        
  layerlibs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: lambda-layer3
      Description: Lambda layer
      CompatibleRuntimes:
        - python3.8
      ContentUri: ../layer.zip
    Metadata:
      BuildMethod: python3.8             # Required to have AWS SAM build this layer
