version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pagerDuty-slack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xg08sfanlri1"
s3_prefix = "pagerDuty-slack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
